### ISSUE TITLE
Make sass folder public

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-theme#11]
@davidrleonard @randyaskin, is that ok to publish sass folder to bower as well, so that px-theme can also be used via sass code?

**Comment by mdwragg** [comment]
Hi @shinxi all variables in the theme can be altered via redefining these ‘custom properties’ in your app code.

Though there’s nothing stopping you forking the repo of course.

I’m not following why you’d want to incorporate these into your app directly?

**Comment by shinxi** [comment]
Our app is created by https://github.com/ServiceMax-Engineering/create-react-app which is a fork of facebook's [create-react-app](https://github.com/facebookincubator/create-react-app), we have to update public/index.html to include px-theme-styles.html, like below
```html
// public/index.html
...
 +    <link rel="import" href="/bower_components/px-theme/px-theme-styles.html">
 +    <style include="px-theme-styles" is="custom-style"></style>
    </body>
  </html>
```
Since we are also using sass, why not directly import the theme sass instead of updating public/index.html, like below

```javascript
//index.js
+ import 'px-theme/sass/px-theme-styles.scss';
import 'index.scss';
```

**Comment by davidrleonard** [comment]
@shinxi I don't think this approach will work for two reasons:

1. In your usage example, you appear to be using webpack(?) to import a .scss file into an index.js file. I assume the resulting CSS that webpack spits out will be dumped into a <style> tag somewhere in the head of your app, either at build time or at runtime. 

To use CSS custom properties like `--px-app-nav-background-color` to do theming in browsers that do not have native web components and CSS custom properties support, you'll need to load some polyfills (webcomponentsjs). The webcomponentsjs ShadyCSS polyfill allows browsers without native features to use CSS custom properties but requires that <style> tags with custom properties have some attributes. 

For Polymer 1.x/webcomponents v0, you'll need to define CSS properties like this:

```
<!-- in index.html -->

<!-- Define inline -->
<style is="custom-style">
  html {
    --px-app-nav-background-color: red;
  }
</style>

<!-- Load from file -->
<style is="custom-style" include="my-app-theme"></style>
```

For Polymer 2.x/webcomponents v1, you'll need to define CSS properties like this:

```
<!-- in index.html -->

<!-- Define inline -->
<custom-style>
  <style>
    html {
      --px-app-nav-background-color: red;
    }
  </style>
</custom-style>

<!-- Load from file -->
<custom-style>
  <style include="my-app-theme"></style>
</custom-style>
```

Unless your webpack build system or node-sass configuration is setup to add these attributes, you won't be able to just build CSS with custom properties and mix it in with all your other app CSS.

2. This isn't how we recommend you theme components. Most component CSS custom properties are relatively high level and are meant to be themed at the app level. You can define multiple themes for the same component in an app by adding a class to the component and defining custom properties for that class, but we generally recommend you not do that. Most components have attributes/properties to configure their state, and CSS custom properties to set all the colors for all the states. We'd recommend you fork px-theme and build your own theme that sets these properties once for the whole app, rather than importing px-theme-styles in one or more places and redefining some of the CSS properties included there.
